package Default;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alu54279423k
 */
public class ScoreBoard extends javax.swing.JPanel {

    /**
     * Creates new form ScoreBoard
     */
    private int score = 0;
    
    public ScoreBoard() {
        initComponents();
        refresh();
    }
    
    public void incrementScore() {
        score = score + 2;
        refresh();
    }
    
    public void decreaseScore() {
        score = score - 2;
        refresh();
    }
    
    public void refresh() {
        jLabel1.setText("Score: " + score);
    }
    
    public void resetScore() {
        score = 0;
        jLabel1.setText("Score: " + score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Score: 0");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
